# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f22baaf3241d470daba47870b19c03eead46e5c608f30af70344b59fda95f9588ee8620bdf4ed11cd7397393f8c02bad3232d9a9a660ccbcd054cfa65d27a96b

test:
  secret_key_base: 4440eb0aa6b4431ff5a857fcf0a0b2cee481ea9bbfba81d0e54d7bba2061249b65f06cc6a80d61e669800f6ef6d6e8147f50c559d6ebf225db18a1ddada1413d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
